language: nix

os:
  - linux
arch:
  - amd64
  - ppc64le

env:
  - EMACS_CI=emacs-24-4
  - EMACS_CI=emacs-25-3
  - EMACS_CI=emacs-26-3
  - EMACS_CI=emacs-snapshot

install:
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)

script:
  - bash <(make test)
